# Configuration version -- DO NOT CHANGE!
global:
  config-version: 0.1

# Configuration relating to Wildfire's Female Gender Mod
mod:
  # The packet format used for mod data reads/writes
  # 2 supports versions 2.8.1 to 3.0.1
  # 3 supports versions 3.1.0 to 4.0.0
  # 4 supports versions 4.0.1 to [T.B.D.]
  # Undocumented protocols will cause this plugin to disable itself on launch.
  protocol: 4
