# Configuration version -- DO NOT CHANGE!
config-version: 0.2

# Configuration relating to Wildfire's Female Gender Mod
mod:
  # The packet format used for mod data reads/writes
  # For a list of protocols and their supported mod versions, refer to https://modrinth.com/plugin/female-gender-spigot
  # -1 will use the newest known protocol, so that you won't need to change this every mod and plugin update.
  # Undocumented protocols will cause this plugin to disable itself on launch.
  protocol: -1
