name: Female-Gender-Mod-Plugin
version: '${project.version}'
main: dbrighthd.wildfiregendermodplugin.GenderModPlugin
api-version: '1.21'
authors: [ 'dbrighthd', 'Stigstille', 'winnpixie', 'UnFamousSoul' ]
folia-supported: true